--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.689.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2021. 11. 08. 23:46:32
-- Server version: 10.4.21
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO football.leagues(`ID(L)`, LName, ShortName, Nation) VALUES
(1, 'English Premier League', 'EPL', 'England'),
(2, 'La Liga Santander', 'LaLiga', 'Spain'),
(3, 'Bundesliga', 'BL1', 'Germany'),
(4, 'Ligue 1 Uber Eats', 'Ligue1', 'France'),
(5, 'Seria A TIM', 'SeriaA', 'Italy');