--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.689.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2021. 11. 07. 22:28:01
-- Server version: 10.4.21
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO football.players(ID, League, Team, Name, Nationality, Position, Age, ShirtNumber) VALUES
(1, 'EPL', 'Arsenal', 'Aaron Ramsdale', 'England', 'GK', 23, 32),
(2, 'EPL', 'Arsenal', 'Calum Chambers', 'England', 'DEF', 26, 21),
(3, 'EPL', 'Arsenal', 'Gabriel', 'Brasil', 'DEF', 23, 6),
(4, 'EPL', 'Arsenal', 'Rob Holding', 'England', 'DEF', 26, 16),
(5, 'EPL', 'Arsenal', 'Sead Kolasinac', 'Bosnia and Herzegovina', 'DEF', 28, 31),
(6, 'EPL', 'Arsenal', 'Ainsley Maitland-Niles', 'England', 'DEF', 24, 15),
(7, 'EPL', 'Arsenal', 'Nuno Tavares', 'Portugal', 'DEF', 21, 20),
(8, 'EPL', 'Arsenal', 'Kieran Tierney', 'Scotland', 'DEF', 24, 3),
(9, 'EPL', 'Arsenal', 'Albert Sambi Lokonga', 'Belgium', 'MID', 22, 23),
(10, 'EPL', 'Arsenal', 'Martin Odegaard', 'Norway', 'MID', 22, 8),
(11, 'EPL', 'Arsenal', 'Thomas Partey', 'Ghana', 'MID', 28, 5),
(12, 'EPL', 'Arsenal', 'Bukayo Saka', 'England', 'MID', 20, 7),
(13, 'EPL', 'Arsenal', 'Smith Rowe', 'England', 'MID', 21, 10),
(14, 'EPL', 'Arsenal', 'Granit Xhaka', 'Switzerland', 'MID', 29, 34),
(15, 'EPL', 'Arsenal', 'Pierre-Emerick Aubameyang', 'Gabon', 'ATT', 32, 14),
(16, 'EPL', 'Arsenal', 'Alexandre Lacazette', 'France', 'ATT', 30, 9),
(17, 'EPL', 'Arsenal', 'Nicolas Pepe', 'Ivory Coast', 'ATT', 26, 19),
(18, 'EPL', 'Aston Villa', 'Emiliano Martinez', 'Argentina', 'GK', 29, 1),
(19, 'EPL', 'Aston Villa', 'Matty Cash', 'Poland', 'DEF', 24, 2),
(20, 'EPL', 'Aston Villa', 'Ezri Konsa', 'England', 'DEF', 24, 4),
(21, 'EPL', 'Aston Villa', 'Tyrone Mings', 'England', 'DEF', 28, 5),
(22, 'EPL', 'Aston Villa', 'Matt Targett', 'England', 'DEF', 26, 3),
(23, 'EPL', 'Aston Villa', 'Axel Tuanzabe', 'England', 'DEF', 23, 16),
(24, 'EPL', 'Aston Villa', 'Emiliano Buendia', 'Argentina', 'MID', 24, 10),
(25, 'EPL', 'Aston Villa', 'Anwar El-Ghazi', 'Netherlands', 'MID', 26, 21),
(26, 'EPL', 'Aston Villa', 'Douglas Luiz', 'Brasil', 'MID', 23, 6),
(27, 'EPL', 'Aston Villa', 'John McGinn', 'Scotland', 'MID', 27, 7),
(28, 'EPL', 'Aston Villa', 'Marvelous Nakamba', 'Zimbabwe', 'MID', 27, 19),
(29, 'EPL', 'Aston Villa', 'Jacob Ramsey', 'England', 'MID', 20, 41),
(30, 'EPL', 'Aston Villa', 'Ashley Young', 'England', 'MID', 36, 18),
(31, 'EPL', 'Aston Villa', 'Leon Bailey', 'Jamaica', 'ATT', 24, 31),
(32, 'EPL', 'Aston Villa', 'Danny Ings', 'England', 'ATT', 29, 20),
(33, 'EPL', 'Aston Villa', 'Bertrand Traore', 'Burkina Faso', 'ATT', 26, 15);