--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.689.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2021. 11. 07. 22:09:49
-- Server version: 10.4.21
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO football.players(ID, League, Team, Name, Nationality, Position, Age, ShirtNumber) VALUES
(1, 'EPL', 'Arsenal', 'Aaron Ramsdale', 'England', 'GK', 23, 32),
(2, 'EPL', 'Arsenal', 'Calum Chambers', 'England', 'DEF', 26, 21),
(3, 'EPL', 'Arsenal', 'Gabriel', 'Brasil', 'DEF', 23, 6),
(4, 'EPL', 'Arsenal', 'Rob Holding', 'England', 'DEF', 26, 16),
(5, 'EPL', 'Arsenal', 'Sead Kolasinac', 'Bosnia and Herzegovina', 'DEF', 28, 31),
(6, 'EPL', 'Arsenal', 'Ainsley Maitland-Niles', 'England', 'DEF', 24, 15),
(7, 'EPL', 'Arsenal', 'Nuno Tavares', 'Portugal', 'DEF', 21, 20),
(8, 'EPL', 'Arsenal', 'Kieran Tierney', 'Scotland', 'DEF', 24, 3),
(9, 'EPL', 'Arsenal', 'Albert Sambi Lokonga', 'Belgium', 'MID', 22, 23),
(10, 'EPL', 'Arsenal', 'Martin Odegaard', 'Norway', 'MID', 22, 8),
(11, 'EPL', 'Arsenal', 'Thomas Partey', 'Ghana', 'MID', 28, 5),
(12, 'EPL', 'Arsenal', 'Bukayo Saka', 'England', 'MID', 20, 7),
(13, 'EPL', 'Arsenal', 'Smith Rowe', 'England', 'MID', 21, 10),
(14, 'EPL', 'Arsenal', 'Granit Xhaka', 'Switzerland', 'MID', 29, 34),
(15, 'EPL', 'Arsenal', 'Pierre-Emerick Aubameyang', 'Gabon', 'ATT', 32, 14),
(16, 'EPL', 'Arsenal', 'Alexandre Lacazette', 'France', 'ATT', 30, 9),
(17, 'EPL', 'Arsenal', 'Nicolas Pepe', 'Ivory Coast', 'ATT', 26, 19),
(18, 'EPL', 'Aston Villa', 'Emiliano Martinez', 'Argentina', 'GK', 29, 1);